### ISSUE TITLE
obsolete header "WProgram.h"

### ISSUE THREAD

**Issue by gicking** [LachlanGunn/oic#2]
just stumbled across your oic library - good work!

Just one thing: the header "WProgram.h" is no longer supported / required since [Arduino version 1.0](https://www.arduino.cc/en/Reference/Changes).
Fix is simple: just comment "#include <WProgram.h>" in line 29 of file "scpiparser.cpp".

Tested and works :-)

**Comment by gicking** [comment]
PS: one more thing. I have bundled the "Meter" example to the folder required for (new) Arduino libs -> copy to user lib folder provides a ready-made example out of the box.

File is stored [here](https://www.dropbox.com/s/9nh1tmag1quqole/ArduinoSCPIParser.zip?dl=0)

**Comment by LachlanGunn** [comment]
Thanks for the issue, and apologies for the delay---I had been logged out for a while.  I will update as soon as I have some free time for this.
