### ISSUE TITLE
Compilation warning

### ISSUE THREAD

**Issue by profeta64** [LachlanGunn/oic#4]
The compiler givers the following warning during the compilation:

> ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]

I have inserted in my code:
`#pragma GCC diagnostic ignored "-Wwrite-strings"`

Example of my definition for a command:
Include of the command:
`scpi_register_command(ctx.command_tree, SCPI_CL_SAMELEVEL, "*IDN?", 5, "*IDN?", 5, CMD_identify);`
Function definition:
`scpi_error_t CMD_identify(struct scpi_parser_context* context, struct scpi_token* command);`

Are there any other solutions?

**Comment by LachlanGunn** [comment]
Sorry for the late response&mdash;I have had a go at fixing this in #5, but I wasn't able to reproduce with with the Arduino IDE in Debian Sid, only compiling as follows:
```
avr-gcc -Wall -Werror -Wno-sign-compare -I/usr/share/arduino/hardware/arduino/cores/arduino/ -I/usr/lib/avr/include/ -I/usr/share/arduino/hardware/arduino/variants/standard/ -D__AVR_ATmega328P__ -c scpiparser.cpp
```
So if you have moment  to check whether this fixes things with your configuration, then I would be greatly appreciative.
